baseURL = "https://cobot-arminlausterer.github.io"
languageCode = "de-de"
theme = "lausterer"
title = "Cobot - Armin Lausterer"
[[menu.main]]
name = "Trainings"
url = "https://armin-lausterer.de/online-trainings/"
weight = 2
